spring.application.name=Travel

# H2コンソール有効化
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# メモリ型DB
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#spring.datasource.url=jdbc:postgresql://dpg-d4d9u8v5r7bs73arluj0-a.singapore-postgres.render.com/travel_postgres_0e08
#spring.datasource.username=travel_postgres_0e08_user
#spring.datasource.password=cjTk9ldmAyvlKrLomK2xZKdXWolFRvvJ
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
#spring.datasource.username=postgres.qkrjbdlsvqhaqwxqngys
#spring.datasource.password=
#spring.datasource.driver-class-name=org.postgresql.Driver


# JPA設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#セキュリティ無効化（本番では削除）
#spring.security.enabled=false

# 起動後、ブラウザでアクセス
# http://localhost:8080/h2-console
# JDBC URL: jdbc:h2:mem:testdb
# ユーザー: sa　パスワード: 空

server.port=${PORT:8080}
