spring.application.name=Travel

# H2コンソール有効化
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
## メモリ型DB、エクリプスで起動する時はH2を使うので下4行有効
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#ここから下はpostgreSQL

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.qkrjbdlsvqhaqwxqngys
spring.datasource.password=TravelApp2025!
spring.datasource.driver-class-name=org.postgresql.Driver

# ★Supabase 無料枠は接続数が10〜15なので上限5に制限する
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=20000

# JPA設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#セキュリティ無効化（本番では削除）
#spring.security.enabled=false

# エクリプス使用時にH2を見に行く時、起動後、ブラウザでアクセス
# http://localhost:8080/h2-console
# JDBC URL: jdbc:h2:mem:testdb
# ユーザー: sa　パスワード: 空

server.port=${PORT:8080}
